export const DEFAULT_REQUEST_TIMEOUT_IN_MS = 10000;
export const DEFAULT_QUERY_STALE_TIME_IN_MS = 300000;
export const DEFAULT_COOKIE_AUTH_TOKEN_KEY = 'X-XSR-AUTH-TOKEN';

export const HTTP_STATUS_CODE = {
  HTTP_OK: 200,
  HTTP_CREATED: 201,
  HTTP_NO_CONTENT: 204,
  HTTP_BAD_REQUEST: 400,
  HTTP_UNAUTHORIZED: 401,
  HTTP_FORBIDDEN: 403,
  HTTP_NOT_FOUND: 404,
  HTTP_SESSION_EXPIRED: 419,
  HTTP_UNPROCESSABLE_ENTITY: 422
}

export const QUERY_KEYS = {
  AUTH_SIGN_UP: 'auth_sign_up',
  AUTH_LOGIN: 'auth_login',
  AUTH_LOGOUT: 'auth_logout',
  AUTH_CURRENT_INFORMATION: 'auth_current_information',
  AUTH_UPDATE_CURRENT_INFORMATION: 'auth_update_current_information',
  AUTH_UPDATE_CURRENT_PASSWORD: 'auth_update_current_password',
}
